title: Christian Johnson's Site
description: >
  Homelab projects, IT journey, and blog — all in one place.

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: "blog"
    values:
      layout: default

baseurl: ""
permalink: pretty
