title: Christian Johnson's Blog
email: christian@johnsonfamilyhub.com
description: >
  Documenting my journey into homelabs, automation, and self-hosting.

url: "https://johnsonfamilyhub.com"
baseurl: "/blog"  # blog lives under this subpath

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
